$ErrorActionPreference = "Stop"

$SetupDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RootDir = Split-Path -Parent $SetupDir
$EnvFile = Join-Path $RootDir ".env"

function Prompt-Value {
  param(
    [string]$Label,
    [string]$Default = ""
  )
  if ($Default) {
    $Value = Read-Host "$Label [$Default]"
    if ([string]::IsNullOrWhiteSpace($Value)) { return $Default }
    return $Value
  }
  return Read-Host $Label
}

function Prompt-SecretValue {
  param([string]$Label)
  $Secure = Read-Host $Label -AsSecureString
  $Ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Secure)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($Ptr)
  } finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($Ptr)
  }
}

function Confirm-Step {
  param(
    [string]$Label,
    [string]$Default = "y"
  )
  $Value = Read-Host "$Label [$Default]"
  if ([string]::IsNullOrWhiteSpace($Value)) { $Value = $Default }
  return $Value -match "^[Yy]"
}

function Escape-EnvValue {
  param([string]$Value)
  if ($null -eq $Value) { return "" }
  return $Value.Replace("\", "\\").Replace('"', '\"')
}

function Add-EnvLine {
  param(
    [string]$Key,
    [string]$Value
  )
  if (-not [string]::IsNullOrWhiteSpace($Value)) {
    Add-Content -Path $EnvFile -Value "$Key=`"$(Escape-EnvValue $Value)`""
  }
}

Write-Host "KnightAuraChess setup"
Write-Host "This creates a local .env, installs dependencies, and validates Cloudflare config."
Write-Host "Secrets stay local and are not committed."
Write-Host ""

$SkipEnv = $false
if (Test-Path $EnvFile) {
  if (Confirm-Step ".env already exists. Back it up and replace it?" "n") {
    $Stamp = Get-Date -Format "yyyyMMddHHmmss"
    Copy-Item $EnvFile "$EnvFile.backup.$Stamp"
  } else {
    Write-Host "Keeping existing .env. Skipping env generation."
    $SkipEnv = $true
  }
}

if (-not $SkipEnv) {
  $FirebaseProjectId = Prompt-Value "Firebase project ID"
  $FirebaseApiKey = Prompt-SecretValue "Firebase web API key"
  $FirebaseConfigJson = Prompt-Value "Optional full Firebase web config JSON"
  $AiDifficulty = Prompt-Value "Default AI difficulty (easy|medium|hard|expert)" "medium"
  $TextAiModel = Prompt-Value "Cloudflare Workers AI model" "@cf/meta/llama-3-8b-instruct"
  $MoveApiEnabled = Prompt-Value "Enable /api/move strict backend? (true|false)" "true"

  $BackendProjectId = Prompt-Value "Backend Firebase project ID" $FirebaseProjectId
  $BackendWebApiKey = Prompt-SecretValue "Backend Firebase web API key"
  $ServiceAccountEmail = Prompt-Value "Optional Firebase service account email"
  $ServiceAccountPrivateKey = Prompt-SecretValue "Optional Firebase service account private key with \n escapes"
  $UpstreamUrl = Prompt-Value "Optional hosted text AI upstream URL"
  $UpstreamToken = Prompt-SecretValue "Optional hosted text AI bearer token"

  Set-Content -Path $EnvFile -Value @(
    "# Local KnightAuraChess environment",
    "# Generated by setup/run.ps1. Do not commit real secrets."
  )

  Add-EnvLine "VITE_FIREBASE_PROJECT_ID" $FirebaseProjectId
  Add-EnvLine "VITE_FIREBASE_API_KEY" $FirebaseApiKey
  Add-EnvLine "VITE_FIREBASE_CONFIG" $FirebaseConfigJson
  Add-EnvLine "VITE_AI_DIFFICULTY" $AiDifficulty
  Add-EnvLine "VITE_TEXT_AI_BASE_URL" "/api/text-ai"
  Add-EnvLine "VITE_MOVE_API_ENABLED" $MoveApiEnabled
  Add-EnvLine "VITE_MOVE_API_STRICT" $MoveApiEnabled
  Add-EnvLine "VITE_MOVE_API_URL" "/api/move"
  Add-EnvLine "FIREBASE_PROJECT_ID" $BackendProjectId
  Add-EnvLine "FIREBASE_WEB_API_KEY" $BackendWebApiKey
  Add-EnvLine "FIREBASE_SERVICE_ACCOUNT_EMAIL" $ServiceAccountEmail
  Add-EnvLine "FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY" $ServiceAccountPrivateKey
  Add-EnvLine "TEXT_AI_MODEL" $TextAiModel
  Add-EnvLine "TEXT_AI_UPSTREAM_URL" $UpstreamUrl
  Add-EnvLine "TEXT_AI_UPSTREAM_AUTH_BEARER" $UpstreamToken

  Write-Host "Wrote .env"
}

if (Confirm-Step "Install npm dependencies?" "y") {
  npm install
}

npm run validate:cloudflare

if (Confirm-Step "Run production build now?" "y") {
  npm run build
}

Write-Host ""
Write-Host "Setup complete."
Write-Host "Run npm run dev to start the app."
