#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

prompt() {
  local label="$1"
  local default_value="${2:-}"
  local value
  if [[ -n "$default_value" ]]; then
    read -r -p "$label [$default_value]: " value
    printf '%s' "${value:-$default_value}"
  else
    read -r -p "$label: " value
    printf '%s' "$value"
  fi
}

prompt_secret() {
  local label="$1"
  local value
  read -r -s -p "$label: " value
  printf '\n' >&2
  printf '%s' "$value"
}

yes_no() {
  local label="$1"
  local default_value="${2:-y}"
  local value
  read -r -p "$label [$default_value]: " value
  value="${value:-$default_value}"
  [[ "$value" =~ ^[Yy] ]]
}

escape_env() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

write_env_line() {
  local key="$1"
  local value="$2"
  if [[ -n "$value" ]]; then
    printf '%s="%s"\n' "$key" "$(escape_env "$value")" >> "$ENV_FILE"
  fi
}

echo "KnightAuraChess setup"
echo "This creates a local .env, installs dependencies, and validates Cloudflare config."
echo "Secrets stay local and are not committed."
echo

if [[ -f "$ENV_FILE" ]]; then
  if yes_no ".env already exists. Back it up and replace it?" "n"; then
    cp "$ENV_FILE" "$ENV_FILE.backup.$(date +%Y%m%d%H%M%S)"
  else
    echo "Keeping existing .env. Skipping env generation."
    SKIP_ENV=1
  fi
fi

if [[ "${SKIP_ENV:-0}" != "1" ]]; then
  firebase_project_id="$(prompt "Firebase project ID")"
  firebase_api_key="$(prompt_secret "Firebase web API key")"
  firebase_config_json="$(prompt "Optional full Firebase web config JSON" "")"
  ai_difficulty="$(prompt "Default AI difficulty (easy|medium|hard|expert)" "medium")"
  text_ai_model="$(prompt "Cloudflare Workers AI model" "@cf/meta/llama-3-8b-instruct")"
  move_api_enabled="$(prompt "Enable /api/move strict backend? (true|false)" "true")"

  backend_project_id="$(prompt "Backend Firebase project ID" "$firebase_project_id")"
  backend_web_api_key="$(prompt_secret "Backend Firebase web API key")"
  service_account_email="$(prompt "Optional Firebase service account email" "")"
  service_account_private_key="$(prompt_secret "Optional Firebase service account private key with \\n escapes")"
  upstream_url="$(prompt "Optional hosted text AI upstream URL" "")"
  upstream_token="$(prompt_secret "Optional hosted text AI bearer token")"

  cat > "$ENV_FILE" <<'ENV_HEADER'
# Local KnightAuraChess environment
# Generated by setup/run.sh. Do not commit real secrets.
ENV_HEADER

  write_env_line "VITE_FIREBASE_PROJECT_ID" "$firebase_project_id"
  write_env_line "VITE_FIREBASE_API_KEY" "$firebase_api_key"
  write_env_line "VITE_FIREBASE_CONFIG" "$firebase_config_json"
  write_env_line "VITE_AI_DIFFICULTY" "$ai_difficulty"
  write_env_line "VITE_TEXT_AI_BASE_URL" "/api/text-ai"
  write_env_line "VITE_MOVE_API_ENABLED" "$move_api_enabled"
  write_env_line "VITE_MOVE_API_STRICT" "$move_api_enabled"
  write_env_line "VITE_MOVE_API_URL" "/api/move"
  write_env_line "FIREBASE_PROJECT_ID" "$backend_project_id"
  write_env_line "FIREBASE_WEB_API_KEY" "$backend_web_api_key"
  write_env_line "FIREBASE_SERVICE_ACCOUNT_EMAIL" "$service_account_email"
  write_env_line "FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY" "$service_account_private_key"
  write_env_line "TEXT_AI_MODEL" "$text_ai_model"
  write_env_line "TEXT_AI_UPSTREAM_URL" "$upstream_url"
  write_env_line "TEXT_AI_UPSTREAM_AUTH_BEARER" "$upstream_token"

  echo "Wrote .env"
fi

if yes_no "Install npm dependencies?" "y"; then
  npm install
fi

npm run validate:cloudflare

if yes_no "Run production build now?" "y"; then
  npm run build
fi

echo
echo "Setup complete."
echo "Run npm run dev to start the app."
